### ISSUE TITLE
No such file or directory in CATENA ./tools/TextPro2.0/

### ISSUE THREAD

**Issue by sriram7797** [paramitamirza/CATENA#3]
java -Xmx6G -jar ./target/CATENA-1.0.3.jar -i /root/dater/data/catena_input.xmlsample.txt.info.xml.tml -l ./models/CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model -g ./models/CoNLL2009-ST-English-ALL.anna-3.3.postagger.model -p ./models/CoNLL2009-ST-English-ALL.anna-3.3.parser.model -x ./tools/TextPro2.0/ -d ./models/catena-event-dct.model -t ./models/catena-event-timex.model -e ./models/catena-event-event.model -c ./models/catena-causal-event-event.model > /root/dater/data/neural_input.tml

I ran the above command.. i am getting following error...

Convert TimeML files to column format...
Exception in thread "main" java.io.FileNotFoundException: ./tools/TextPro2.0/temp_catena_input.xmlsample.txt.info.xml.txt.txp (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.util.Scanner.<init>(Scanner.java:611)
        at catena.parser.TextProParser.run(TextProParser.java:140)
        at catena.parser.TimeMLToColumns.convert(TimeMLToColumns.java:491)
        at catena.parser.TimeMLToColumns.convert(TimeMLToColumns.java:514)
        at catena.Temporal.filePreprocessing(Temporal.java:77)
        at catena.Temporal.extractRelations(Temporal.java:734)
        at catena.Catena.extractRelations(Catena.java:489)
        at catena.Catena.extractRelationsString(Catena.java:402)
        at catena.Catena.main(Catena.java:89)

Can anyone please help me to fix this?

**Comment by WxZy530** [comment]
Do you solve the problem?It seems that TextPro2.0 doesn't work

**Comment by paramitamirza** [comment]
Because you have to download it from the TextPro link I put under the **Text processing tools** .
Here is the download link: http://textpro.fbk.eu/distribution
